import { useAppointmentStore } from '../store/appointmentStore';
import { usePatientStore } from '../store/patientStore';
import { useDoctorStore } from '../store/doctorStore';

// Re-export stores as hooks for easier imports if preferred, 
// or add specific logic here.
// For now, we just export the hooks generated by Zustand.

export const useAppointments = useAppointmentStore;
export const usePatient = usePatientStore;
export const useDoctors = useDoctorStore;
